language: objective-c
osx_image: xcode6.4
before_install:
    - (ruby --version)
    - sudo motion update
gemfile:
  - Gemfile
script:
    - bundle install
    - bundle exec rake pod:install > /dev/null
    - bundle exec rake clean
    - bundle exec rake spec --trace
