language: objective-c
osx_image: xcode7
before_install:
  - mkdir -p ~/Library/RubyMotion
  - "(ruby --version)"
  - sudo chown -R travis ~/Library/RubyMotion
  - mkdir -p ~/Library/RubyMotion/build
  - sudo motion update
gemfile:
  - Gemfile
script:
  - bundle install
  - bundle exec rake pod:install > /dev/null
  - bundle exec rake clean
  - bundle exec rake spec
deploy:
  provider: rubygems
  api_key:
    secure: lWW06/l8qICHPWYvRrBkDdAl/1t7br4dvFvxK5IMx2p0SwP2vIP2zyQwYLrbBY/jv/aJ4zhzdcQ4T9lqbiRZnomzK6tBCPyX4lt6qrf9DP6stPybojxAjzyY7PTShXeBkzu7QA9YZqFizBFmEHncEvmy13N5Eama0g/QBOUhai1DqNqk6jKx2jqsMp+P97rTWg2bcyEv2AzSyeUfDIDjadsZzF9n3IqeuxQU60gxBaWWrY+YVOvZoCca2sYZzafGjLdaf9wZuo8NJ5zHP2NdPgAoKYy1hahBq07l53u+D6uGMdkX6ZjOGk/2BK3KT+WQuDA/1FhNSQ++ExE7y36ayC4yNqGwijMk6Pqz+VmN/ztevJRiIvSqiH4/2xS/pTb2Rxfoz/BQyO+q2E5VSVDfGT4I5EunqvRycfjDm7AQiZfD5L95f2Noy/VZoaoQes1WlzpbABkjDqON1uH0kA3UiGco6AF38Zf+W6eG9eLOshgS8jnuYHQ4Fs5+035sWqzPlS2i7nxHMtkXU/fm7o4D0iSXXDrjZ55KjQBveGdhZH9bZJk1Naj8xk2oPBXDGx3dH++y3EyPJwMR4M5i3Hao3c3qG5dbyWAXm/mxmeUt2Me6PbOVFaii+pJsI38LSNBKz1YwflmqE1DdUoK2qcQV9lXiDTyDMo+2OUJV+FjF8qE=
